<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.nguiland.microservice</groupId>
    <artifactId>nguiland-ms-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.optimagrowth</groupId>
  <artifactId>ostock-ms-parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>ostock-ms-parent</name>
  <description>Microservice Parent</description>
  <properties>
    <orm.version>0.0.1-SNAPSHOT</orm.version>
    <dto.version>0.0.1-SNAPSHOT</dto.version>
    <cross-cutting-concerns.version>0.0.1-SNAPSHOT</cross-cutting-concerns.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.optimagrowth</groupId>
        <artifactId>orm</artifactId>
        <version>${orm.version}</version>
      </dependency>
      <dependency>
        <groupId>com.optimagrowth</groupId>
        <artifactId>dto</artifactId>
        <version>${dto.version}</version>
      </dependency>
      <dependency>
        <groupId>com.optimagrowth</groupId>
        <artifactId>cross-cutting-concerns</artifactId>
        <version>${cross-cutting-concerns.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>